package cloud.autotests.tests;

import cloud.autotests.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Selenide.open;
import static com.codeborne.selenide.Selenide.title;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class GeneratedTests extends TestBase {
    @Test
    @Description("Soon to be implemented by you (or QA.GURU engineers)")
    @DisplayName("Проверка авторизации на сайте https://www.drive2.ru")
    void generatedTest() {
        step("Зайти на сайт ' https://www.drive2.ru '", () -> {
            step("// todo: just add selenium action");
        });

        step("Нажать кнопку \"Войти\" в правом верхнем углу сайта.", () -> {
            step("// todo: just add selenium action");
        });

        step("Ввести Email в поле \"Email\" 'sukhoff1@mail.ru'", () -> {
            step("// todo: just add selenium action");
        });

        step("Ввести пароль в поле \"пароль\" 'sukhoff1'", () -> {
            step("// todo: just add selenium action");
        });

        step("Поставить ЛКМ галочку в поле \"Запомнить меня\"", () -> {
            step("// todo: just add selenium action");
        });

        step("Нажать ЛКМ по кнопке \"Войти\"", () -> {
            step("// todo: just add selenium action");
        });

        step("На главной странице нажать по аватару ЛКМ.", () -> {
            step("// todo: just add selenium action");
        });

        step("Проверить наличие текста 'Dogmach' в профиле аккаунта.", () -> {
            step("// todo: just add selenium action");
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://www.drive2.ru'", () ->
            open("https://www.drive2.ru"));

        step("Page title should have text '403 — Доступ запрещён'", () -> {
            String expectedTitle = "403 — Доступ запрещён";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://www.drive2.ru'", () ->
            open("https://www.drive2.ru"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}